#define TK_SEMI                            1
#define TK_CREATE                          2
#define TK_TABLE                           3
#define TK_IF                              4
#define TK_NOT                             5
#define TK_EXISTS                          6
#define TK_LP                              7
#define TK_RP                              8
#define TK_COMMA                           9
#define TK_ID                             10
#define TK_INT                            11
#define TK_DEFAULT                        12
#define TK_ARG                            13
#define TK_FLOAT                          14
#define TK_HEX                            15
#define TK_ADD                            16
#define TK_SUB                            17
#define TK_NULL                           18
#define TK_DROP                           19
#define TK_INSERT                         20
#define TK_INTO                           21
#define TK_VALUES                         22
#define TK_UPDATE                         23
#define TK_SET                            24
#define TK_EQ                             25
#define TK_DELETE                         26
#define TK_FROM                           27
#define TK_SELECT                         28
#define TK_ON                             29
#define TK_JOIN                           30
#define TK_INNER                          31
#define TK_CROSS                          32
#define TK_LEFT                           33
#define TK_WHERE                          34
#define TK_GROUP                          35
#define TK_BY                             36
#define TK_ORDER                          37
#define TK_ASC                            38
#define TK_DESC                           39
#define TK_LIMIT                          40
#define TK_OFFSET                         41
#define TK_QID                            42
#define TK_SHOW                           43
#define TK_VARIABLES                      44
#define TK_LIKE                           45
#define TK_SUM                            46
#define TK_MIN                            47
#define TK_MAX                            48
#define TK_COUNT                          49
#define TK_MUL                            50
#define TK_AVG                            51
#define TK_ABS                            52
#define TK_ROUND                          53
#define TK_CONCAT                         54
#define TK_LOWER                          55
#define TK_UPPER                          56
#define TK_TRIM                           57
#define TK_LEADING                        58
#define TK_TRAILING                       59
#define TK_BOTH                           60
#define TK_LTRIM                          61
#define TK_RTRIM                          62
#define TK_LENGTH                         63
#define TK_CHAR_LENGTH                    64
#define TK_SUBSTR                         65
#define TK_FOR                            66
#define TK_LOCATE                         67
#define TK_POSITION                       68
#define TK_IN                             69
#define TK_ASCII                          70
#define TK_CURRENT_TIMESTAMP              71
#define TK_CURRENT_TIME                   72
#define TK_CURRENT_DATE                   73
#define TK_CONVERT                        74
#define TK_USING                          75
#define TK_DOT                            76
#define TK_ALIAS                          77
#define TK_QUEST                          78
#define TK_AND                            79
#define TK_OR                             80
#define TK_IS                             81
#define TK_NOTLIKE                        82
#define TK_ISNULL                         83
#define TK_NOTNULL                        84
#define TK_BETWEEN                        85
#define TK_NE                             86
#define TK_GT                             87
#define TK_GE                             88
#define TK_LT                             89
#define TK_LE                             90
#define TK_BITAND                         91
#define TK_BITOR                          92
#define TK_SHL                            93
#define TK_SHR                            94
#define TK_DIV                            95
#define TK_MOD                            96
#define TK_EXP                            97
#define TK_MINUS                          98
#define TK_PLUS                           99
